# Generated by Django 4.0.3 on 2022-03-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_steps', models.IntegerField(choices=[(0, 'step1;step2;step5'), (1, 'step3;step2;step1'), (2, 'step3;step4;step2')], default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='api.customer')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='program', to='api.program')),
            ],
        ),
    ]
